# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 660e16d7296b7e1641d5db5ffd4382a61a205169e070c156d1e867207f2aaf0f334a57a6fcccab798e7f0d66e5e76e07150e08cad1e1fa1df7ec3fe9df50a657

test:
  secret_key_base: 9ce28321b796b898067c8e6ccf8b8ca65e3d561c10bc6ce7a0da9cd28b14c171a6a157e0085329412fc1aeaa2372aeacee947aaddb1caae9d44e698e9e7851e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
